name: CosmicCore
version: '${project.version}'
main: me.viiral.cosmiccore.CosmicCore
api-version: 1.13
authors: [ ViiRal ]
depend:
  - WorldGuard
  - Factions
commands:
  givecrystal:
    description: crystals
  givemask:
    description: masks
  giveextractor:
    description: extractor
  giveskin:
    description: skins
  heal:
    description: heal
  bless:
    description: bless
