package me.viiral.cosmiccore.modules.user.effects;

public enum EffectType {

    IMMUNE_TO_FREEZES, // DONE
    IMMUNE_TO_SLOWNESS, // DONE
    IMMUNE_TO_TELEBLOCK, // DONE
    IMMUNE_TO_NATURES, // DONE
    IMMUNE_TO_SOULTRAP, // SOUL TRAP NOT CODED IN YET
    IMMUNE_TO_SNIPER, // SNIPER NOT CODED IN YET
    IMMUNE_TO_HEROKILLER, // HERO KILLER NOT CODED IN YET
    IMMUNE_TO_WITCHHAT, // WITCH HAT NOT FULLY CODED IN YET
    IMMUNE_TO_DEEPBLEED_SLOWNESS, // DONE
    IMMUNE_TO_LIFESTEAL, // DONE
    IMMUNE_TO_TANK, // DONE
    IMMUNE_TO_GUARDIANS, // GUARDIANS NOT CODED IN YET
    IMMUNE_TO_CAGE, // PETS NOT CODED IN YET
    IMMUNE_TO_KNOCKBACK, // DONE
    IMMUNE_TO_SABOTAGE, // SABOTAGE NOT CODED In YET
    IMMUNE_TO_TRAP, // DONE
    IMMUNE_TO_AMULET_OF_CORRUPTION, // AMULET OF CORRUPTION NOT CODED IN YET
    IMMUNE_TO_BANSHEE_HOLY, // PETS NOT CODED IN YET
    IMMUNE_TO_BANSHEE, // PETS NOT CODED IN YET
    IMMUNE_TO_BLOODHOUND, // PETS NOT CODED IN YET
    IMMUNE_TO_FIRE_LAVA,
    CANT_BLOCK_PHOENIX, // DONE
    BLOCK_ROCKET_ESCAPE, // DONE
    BLOCK_ARMORED, // DONE
    BLOCK_PHOENIX, // DONE
    TWO_SELL_PRICES,
    AUTO_BLESS; // DONE


}
